### ISSUE TITLE
how show space in search fragment ?

### ISSUE THREAD

**Issue by samatzp** [nminhanh-git/SpaceSharingFirestore#1]
i show added data in manage activity but not see seacrh fragment ? 
![2020-05-16_18-08-34](https://user-images.githubusercontent.com/50781959/82119442-67304680-97a0-11ea-8742-6facbddb3766.png)
![2020-05-16_18-08-51](https://user-images.githubusercontent.com/50781959/82119443-68fa0a00-97a0-11ea-8ec5-f35ea4d38134.png)
![2020-05-16_18-09-01](https://user-images.githubusercontent.com/50781959/82119445-6992a080-97a0-11ea-92e5-698b1466a997.png)

**Comment by nminhanh-git** [comment]
Sorry for late comment, but I think you've misunderstood the function of this application, so I will close the issue. and of course you can't see the data, because my project is attach with my database in Firestore, so if you change anything in the code, I think it will not function properly.
